nameOverride: polkadot-nft-farcaster-frames
fullnameOverride: polkadot-nft-farcaster-frames
image:
     repository: shritesh99/polkadot-node
     pullPolicy: Always
     tag: latest
node:
     chain: polkadot-nft-farcaster-frames
     command: parachain-template-node
     replicas: 1
     role: full
     customChainspec: true
     customChainspecPath: "/chain-data/chainspec.raw.json"
     chainData:
          database: paritydb
          pruning: archive
          volumeSize: 5Gi
          storageClass: do-block-storage
     chainKeystore:
          mountInMemory:
               enabled: true
     isParachain: true
     collatorRelayChain:
          chain: paseo
          chainData:
               database: paritydb
               pruning: 1000
               storageClass: do-block-storage
               volumeSize: 50Gi
               chainPath: westend2
          chainKeystore:
               mountInMemory:
                    enabled: true
     allowUnsafeRpcMethods: true
     customNodeKey:
          # 12D3KooWBQAxvTmV1n37ypF3LZX92hdbpbGyGqaZx7i9NgVR9hFn
          - 05a88fb628f00c645c94e385d0811038b1720c2b50dcac09e32055dfefb6c1cb
     flags:
          - "--rpc-max-connections 1000"
     perNodeServices:
          relayP2pService:
               enabled: true
               type: NodePort
          paraP2pService:
               enabled: true
               type: NodePort
          setPublicAddressToExternalIp:
               enabled: true
     wasmRuntimeOverridesPath: "/chain-data"
     resources:
          requests:
               cpu: 100m
               memory: 1Gi
          limits:
               memory: 2Gi

# RPC Endpoint
ingress:
     enabled: true
     ingressClassName: nginx
     annotations:
          kubernetes.io/ingress.class: nginx
          external-dns.alpha.kubernetes.io/target: polkadot-node-rpc.rxshri99.live
     host: polkadot-node-rpc.rxshri99.live
extraInitContainers:
     - name: chainspec-mount
       image: shritesh99/polkadot-node:latest
       imagePullPolicy: Always
       securityContext:
            runAsUser: 0
       command: ["/bin/sh"]
       args:
            - -c
            - cp /chain-spec/* /chain-data
       volumeMounts:
            - name: chain-data
              mountPath: /chain-data
